name: boogi_on_and_on
description: MVP onboarding flow for Boogi On & On - Mental Care & Habit Tracker app.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.4.9
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
